### ISSUE TITLE
Incompatible with normal Arduinos (with AVR controller), no example

### ISSUE THREAD

**Issue by RobertSte** [stm32duino/STTS22H#4]
I tried to use this library with normal Arduino (ATmega328P) but there are unclear type definitions and some special I2C Lib instead of the Arduino Wire lib used.

Unlike the statement on the Arduino Website: https://www.arduino.cc/reference/en/libraries/stm32duino-stts22h/
This lib is NOT compatible with the listed Arduino Boards there.

Please correct this!

**Comment by fpistm** [comment]
Hi @RobertSte 

I've made the fix and added an example.
